version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: factus-erp-db
    environment:
      POSTGRES_DB: factus_erp
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: retofactus123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: